language: php

notifications:
  on_success: never
  on_failure: change

branches:
  only:
    - master

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
script:
  - vendor/bin/phpunit
